services:
  frontend:
    container_name: pomodoro_frontend
    build:
      context: .
    environment:
      NODE_ENV: production
    expose:
      - 3000
    networks:
      - app-network

networks:
  app-network:
    name: pomodoro-network
    external: true
